### ISSUE TITLE
Error using Docker image

### ISSUE THREAD

**Issue by nlamirault** [ContainerSolutions/helm-convert#25]
I've got an error using the Docker image : 

```
docker run -ti containersol/helm-convert convert --destination mongodb --name mongodb stable/mongodb
Error: no cached repo found. (try 'helm repo update'). open /root/.helm/repository/cache/stable-index.yaml: no such file or directory
Usage:
  convert [flag] [chart URL | repo/chartname] [...] [flags]

Examples:

  # convert the stable/mongodb chart
  helm convert --destination mongodb --name mongodb stable/mongodb

  # convert chart from a url
  helm convert https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/prometheus-operator

  # convert the stable/mongodb chart with a given values.yaml file
  helm convert -f values.yaml stable/mongodb

  # convert the stable/mongodb chart and override values using --set flag:
  helm convert --set persistence.enabled=true stable/mongodb


Flags:
      --alsologtostderr                  log to standard error as well as files
      --ca-file string                   verify certificates of HTTPS-enabled servers using this CA bundle
      --cert-file string                 identify HTTPS client using this SSL certificate file
      --comments                         add default comments to kustomization.yaml file (default true)
      --dep-up                           run helm dependency update before installing the chart
  -d, --destination string               location to write the chart. If this and tardir are specified, tardir is appended to this
      --force                            convert chart even if the destination directory already exists
  -h, --help                             help for convert
      --home string                      location of your Helm config. Overrides $HELM_HOME (default "/root/.helm")
      --key-file string                  identify HTTPS client using this SSL key file
      --keyring string                   keyring containing public keys (default "/root/.gnupg/pubring.gpg")
      --log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
      --log_dir string                   If non-empty, write log files in this directory
      --logtostderr                      log to standard error instead of files (default true)
      --name string                      release name
      --namespace string                 global namespace to use for the manifests (default "default")
      --password string                  chart repository password
      --prov                             fetch the provenance file, but don't perform verification
      --repo string                      chart repository url where to locate the requested chart
      --set stringArray                  set values on the command line (can specify multiple or separate values with commas: key1=val1,key2=val2)
      --set-file stringArray             set values from respective files specified via the command line (can specify multiple or separate values with commas: key1=path1,key2=path2)
      --set-string stringArray           set STRING values on the command line (can specify multiple or separate values with commas: key1=val1,key2=val2)
      --skip-transformers strings        set a list of transformers that are skipped during the conversion process (can specify multiple or separate values with commas: secret,configmap)
      --stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
      --username string                  chart repository username
  -v, --v Level                          log level for V logs
  -f, --values ValueFiles                specify values in a YAML file or a URL(can specify multiple) (default [])
      --verify                           verify the package against its signature
      --version string                   specific version of a chart. Without this, the latest version is fetched
      --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging

Error: plugin "convert" exited with error
```

**Comment by etiennetremel** [comment]
@nlamirault if you build the docker image from latest master it should work, I updated the alpine base image which include new certificates.
The automatic docker build feature that dockerhub offer has been unlinked for some time now, I asked someone from Container Solutions to have a look but it might take some time..

**Comment by etiennetremel** [comment]
@nlamirault Github <> Docker hub CI build has been fixed, I added the missing `helm repo update` command in the Dockerfile.

I tested your command with v0.5.3, it works:

```bash
$ docker run -ti -v $PWD/mongodb:/mongodb containersol/helm-convert:v0.5.3 convert --destination mongodb --name mongodb stable/mongodb
Destination directory 'mongodb' already exist, override? [y/n] y

$ ls mongodb
Kube-descriptor.yaml kustomization.yaml   mongodb-deploy.yaml  mongodb-pvc.yaml     mongodb-svc.yaml
```

**Comment by brunowego** [comment]
Same issue here.

```sh
docker run -it --rm \
  -v "$PWD"/keycloak:/keycloak \
  docker.io/containersol/helm-convert:v0.5.3 convert \
    --dep-up \
    -d /keycloak \
    --name dev \
    --namespace keycloak-dev \
    https://github.com/codecentric/helm-charts/releases/download/keycloak-11.0.1/keycloak-11.0.1.tgz
```

Error: plugin "convert" exited with error

**Comment by etiennetremel** [comment]
@brunowego if you look at the error message above the one you mentioned it says:

```
Error: parse error in "keycloak/charts/postgresql/charts/common/templates/_secrets.tpl": template: keycloak/charts/postgresql/charts/common/templates/_secrets.tpl:84: function "lookup" not defined
```

It's possible that the `lookup` Helm function was added in Helm v3 which is currently not supported.

**Comment by lodotek** [comment]
Bump. What am I doing wrong here?

```
docker run -ti -v $PWD/mongodb:/mongodb containersol/helm-convert:v0.5.3 convert --destination mongodb --name mongodb stable/mongodb
```

```
Error: Failed to fetch https://kubernetes-charts.storage.googleapis.com/mongodb-7.8.10.tgz : 403 Forbidden
Usage:
  convert [flag] [chart URL | repo/chartname] [...] [flags]

Examples:

  # convert the stable/mongodb chart
  helm convert --destination mongodb --name mongodb stable/mongodb

  # convert chart from a url
  helm convert https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/prometheus-operator

  # convert the stable/mongodb chart with a given values.yaml file
  helm convert -f values.yaml stable/mongodb

  # convert the stable/mongodb chart and override values using --set flag:
  helm convert --set persistence.enabled=true stable/mongodb


Flags:
      --alsologtostderr                  log to standard error as well as files
      --ca-file string                   verify certificates of HTTPS-enabled servers using this CA bundle
      --cert-file string                 identify HTTPS client using this SSL certificate file
      --comments                         add default comments to kustomization.yaml file (default true)
      --dep-up                           run helm dependency update before installing the chart
  -d, --destination string               location to write the chart. If this and tardir are specified, tardir is appended to this
      --force                            convert chart even if the destination directory already exists
  -h, --help                             help for convert
      --home string                      location of your Helm config. Overrides $HELM_HOME (default "/root/.helm")
      --key-file string                  identify HTTPS client using this SSL key file
      --keyring string                   keyring containing public keys (default "/root/.gnupg/pubring.gpg")
      --log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
      --log_dir string                   If non-empty, write log files in this directory
      --logtostderr                      log to standard error instead of files (default true)
      --name string                      release name
      --namespace string                 global namespace to use for the manifests (default "default")
      --password string                  chart repository password
      --prov                             fetch the provenance file, but don't perform verification
      --repo string                      chart repository url where to locate the requested chart
      --set stringArray                  set values on the command line (can specify multiple or separate values with commas: key1=val1,key2=val2)
      --set-file stringArray             set values from respective files specified via the command line (can specify multiple or separate values with commas: key1=path1,key2=path2)
      --set-string stringArray           set STRING values on the command line (can specify multiple or separate values with commas: key1=val1,key2=val2)
      --skip-transformers strings        set a list of transformers that are skipped during the conversion process (can specify multiple or separate values with commas: secret,configmap)
      --stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
      --username string                  chart repository username
  -v, --v Level                          log level for V logs
  -f, --values ValueFiles                specify values in a YAML file or a URL(can specify multiple) (default [])
      --verify                           verify the package against its signature
      --version string                   specific version of a chart. Without this, the latest version is fetched
      --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging

Error: plugin "convert" exited with error

```
🧐

**Comment by lodotek** [comment]
> I've got an error using the Docker image :
> 
> ```
> docker run -ti containersol/helm-convert convert --destination mongodb --name mongodb stable/mongodb
> Error: no cached repo found. (try 'helm repo update'). open /root/.helm/repository/cache/stable-index.yaml: no such file or directory
> Usage:
>   convert [flag] [chart URL | repo/chartname] [...] [flags]
> 
> Examples:
> 
>   # convert the stable/mongodb chart
>   helm convert --destination mongodb --name mongodb stable/mongodb
> 
>   # convert chart from a url
>   helm convert https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/prometheus-operator
> 
>   # convert the stable/mongodb chart with a given values.yaml file
>   helm convert -f values.yaml stable/mongodb
> 
>   # convert the stable/mongodb chart and override values using --set flag:
>   helm convert --set persistence.enabled=true stable/mongodb
> 
> 
> Flags:
>       --alsologtostderr                  log to standard error as well as files
>       --ca-file string                   verify certificates of HTTPS-enabled servers using this CA bundle
>       --cert-file string                 identify HTTPS client using this SSL certificate file
>       --comments                         add default comments to kustomization.yaml file (default true)
>       --dep-up                           run helm dependency update before installing the chart
>   -d, --destination string               location to write the chart. If this and tardir are specified, tardir is appended to this
>       --force                            convert chart even if the destination directory already exists
>   -h, --help                             help for convert
>       --home string                      location of your Helm config. Overrides $HELM_HOME (default "/root/.helm")
>       --key-file string                  identify HTTPS client using this SSL key file
>       --keyring string                   keyring containing public keys (default "/root/.gnupg/pubring.gpg")
>       --log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
>       --log_dir string                   If non-empty, write log files in this directory
>       --logtostderr                      log to standard error instead of files (default true)
>       --name string                      release name
>       --namespace string                 global namespace to use for the manifests (default "default")
>       --password string                  chart repository password
>       --prov                             fetch the provenance file, but don't perform verification
>       --repo string                      chart repository url where to locate the requested chart
>       --set stringArray                  set values on the command line (can specify multiple or separate values with commas: key1=val1,key2=val2)
>       --set-file stringArray             set values from respective files specified via the command line (can specify multiple or separate values with commas: key1=path1,key2=path2)
>       --set-string stringArray           set STRING values on the command line (can specify multiple or separate values with commas: key1=val1,key2=val2)
>       --skip-transformers strings        set a list of transformers that are skipped during the conversion process (can specify multiple or separate values with commas: secret,configmap)
>       --stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
>       --username string                  chart repository username
>   -v, --v Level                          log level for V logs
>   -f, --values ValueFiles                specify values in a YAML file or a URL(can specify multiple) (default [])
>       --verify                           verify the package against its signature
>       --version string                   specific version of a chart. Without this, the latest version is fetched
>       --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging
> 
> Error: plugin "convert" exited with error
> ```

I had a similar issue, I ended up having to do a `touch $HOME/.helm/repository/repositories.yaml`  & `helm repo add stable https://charts.helm.sh/stable && helm repo update`

**Comment by pkit** [comment]
I'm not sure if it's some kind of joke?
Helm `3.6.3` doesn't have `$HOME/.helm/repository/repositories.yaml` file and will never have it.
It's now stored in `$HOME/.config/helm/repositories.yaml`
@etiennetremel what's is the status of `helm-convert` in 2022? Abandoned?
