### ISSUE TITLE
Installation broken on 0.5.1

### ISSUE THREAD

**Issue by eyalzek** [ContainerSolutions/helm-convert#29]
`helm plugin install https://github.com/ContainerSolutions/helm-convert` fails because of the install hook:
https://github.com/ContainerSolutions/helm-convert/blob/v0.5.1/plugin.yaml#L11

specifically here:
https://github.com/ContainerSolutions/helm-convert/blob/v0.5.1/install.sh#L11

since https://github.com/ContainerSolutions/helm-convert/releases/download/v0.5.1/helm-convert_linux_0.5.1.tar.gz does not exist.

**Comment by etiennetremel** [comment]
HI @eyalzek sorry for the inconvenience, I just noticed my token expired after I left the organization. I still have the maintainer role so I managed to upload the missing binaries manually, see: https://github.com/ContainerSolutions/helm-convert/releases/tag/v0.5.1

**Comment by eyalzek** [comment]
Seems to work, thanks!
